# Site settings
title: Maison de learning
SEOTitle: Minki Blog
header-img: img/home-bg.jpg
email: atunh9988@naver.com
description: "안녕하세요. 김민기입니다."
keyword: "deeplearning, flutter, 서비스 기획"
url: "https://minkithub.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     huxprohihu_username:     huxpro
github_username:    minkithub
# twitter_username:   huxpro
facebook_username:  UOSMinki
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: https-minkithub-github-io-minki-github-io

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-163576297-1'            # Format: UA-xxxxxx-xx
ga_domain: https://minkithub.github.io/



# Sidebar settings
sidebar: flase                           # whether or not using Sidebar.
sidebar-about-description: "안녕하세요. 김민기입니다."
sidebar-avatar: /img/tag-bg.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 3            # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true
# post-mathjax: true



# Friends
# friends: [
#     {
#     #     title: "Su",
#     #     href: "http://su.gallery/"
#     # # },{
#     #     title: "예시",
#     #     href: "URL"
#     # },
# ]
